/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dialog;
//blomm

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class MemberFrame extends javax.swing.JFrame {

    private DefaultTableModel model;

    String koneksi = "jdbc:postgresql://localhost:5432/DB_GYM";
    String user = "postgres";
    String password = "masryoo21";

    public MemberFrame() {
        initComponents();

        // Set model JTable
        model = new DefaultTableModel(new Object[]{"ID Member", "Nama", "Tipe Paket", "Coach"}, 0);
        tblMember.setModel(model);

        loadDataTable();
    }

    void loadDataTable() {
        model.setRowCount(0); // clear tabel dulu
        try (Connection conn = DriverManager.getConnection(koneksi, user, password);
                Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery
        ("SELECT * FROM member_gym ORDER BY id_member")) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_member"), // sesuaikan tipe data integer
                    rs.getString("nama"),
                    rs.getString("tipe_paket"),
                    rs.getString("coach")
                });
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error load data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMember = new javax.swing.JTable();
        jlFilm = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 153));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setAlignmentX(1.0F);
        jScrollPane2.setAlignmentY(1.0F);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tblMember.setBorder(new javax.swing.border.MatteBorder(null));
        tblMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Member", "Nama", "Tipe Paket", "Coach"
            }
        ));
        jScrollPane2.setViewportView(tblMember);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 570, 360));

        jlFilm.setBackground(new java.awt.Color(204, 204, 255));
        jlFilm.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jlFilm.setForeground(new java.awt.Color(204, 255, 255));
        jlFilm.setText("DATA MEMBER RYO'S GYM");
        getContentPane().add(jlFilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, -1, 40));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 110, 40));

        Close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Close.setForeground(new java.awt.Color(255, 0, 51));
        Close.setText("X");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        getContentPane().add(Close, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 60, 40));

        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnInsert.setText("INSERT");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 110, 40));

        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 110, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dialog/111.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked

    }//GEN-LAST:event_TabelMouseClicked

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_CloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblMember.getSelectedRow();
        if (row != -1) {
            String id = tblMember.getValueAt(row, 0).toString();
            String nama = tblMember.getValueAt(row, 1).toString();
            String tipe = tblMember.getValueAt(row, 2).toString();
            String coach = tblMember.getValueAt(row, 3).toString();

            DeleteDialog dlg = new DeleteDialog(this, true, id, nama, tipe, coach);
            dlg.setVisible(true);
            if (dlg.isDeleted()) {
                loadDataTable();
                
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblMember.getSelectedRow();
        if (row != -1) {
            String id = tblMember.getValueAt(row, 0).toString();
            String nama = tblMember.getValueAt(row, 1).toString();
            String tipe = tblMember.getValueAt(row, 2).toString();
            String coach = tblMember.getValueAt(row, 3).toString();

            UpdateDialog dlg = new UpdateDialog(this, true, id, nama, tipe, coach);
            dlg.setVisible(true);
            if (dlg.isUpdated()) {
                loadDataTable();
                
            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        InsertDialog dlg = new InsertDialog(this, true);
        dlg.setVisible(true);
        if (dlg.isSaved()) {
            loadDataTable();
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
    try {
        Connection conn = DriverManager.getConnection(
            "jdbc:postgresql://localhost:5432/DB_GYM",
            "postgres",
            "masryoo21"
        );

        String reportPath = "src/Dialog/report1.jasper";
        JasperPrint jp = JasperFillManager.fillReport(reportPath, null, conn);
        JasperViewer.viewReport(jp, false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new MemberFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlFilm;
    private javax.swing.JTable tblMember;
    // End of variables declaration//GEN-END:variables

}
